apiVersion: 1

datasources:
  - name: BusinessMetrics PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: businessmetrics
    user: usuario_readonly
    secureJsonData:
      password: 'ReadOnly123!Secure'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
